### ISSUE TITLE
Hi Justin, I need your help.

### ISSUE THREAD

**Issue by gyuyoung-hwang** [matlab-deep-learning/pix2pix#11]
I really appreciate for your Pix2pix implementation.

So, while following your codes in github, i got some trobules.
code was this : p2pModel = p2p.train(labelFolder, targetFolder, options);

at the initial stage, it seemed to work well,
epoch: 1, it: 50, G: 33.262539 (L1: 0.325226, GAN: 0.739980), D: 0.677450

then, errors are followed below.

Unrecognized method, property or field 'PrepForPlot' for class 'p2p.vis.TrainingPlot'.
 p2p.vis.TrainingPlot/updateImages (line 63)
            displayIm = obj.PrepForPlot(output);

p2p.vis.TrainingPlot/update (line 47)
            obj.updateImages(generator)
p2p.train (line 100)
                    trainingPlot.update(logArgs{:}, g);

Actually, I am Korean, and sorry for using MATLAB in Korean

So I just translated the error in English. I'm sorry

Can you help me please?

after following your code with facades dataset,

I want to apply my dataset( RGB png dataset with RGB jpg dataset).
(Actually, same error happend again on my data. T-T)

**Comment by gyuyoung-hwang** [comment]
I solved that problem
I'm really sorry
I just revised captial letter.
thank you !
 good day~!

**Comment by justinpinkney** [comment]
Thanks for spotting this! I've fixed in the repo too now,
