### ISSUE TITLE
Pix2pix HD

### ISSUE THREAD

**Issue by yimuchunshu** [matlab-deep-learning/pix2pix#14]
Any plan for Pix2pix HD?

**Comment by justinpinkney** [comment]
I don't currently have any plans to add pix2pix hd.

**Comment by justinpinkney** [comment]
There is now a documentation example of pix2pixHD as part of MATLAB's Computer Vision Toolbox: https://uk.mathworks.com/help/vision/ug/generate-image-from-segmentation-map-using-deep-learning.html
