### ISSUE TITLE
Is the exact same image augmentation on the A and B datasets？

### ISSUE THREAD

**Issue by momo-love** [matlab-deep-learning/pix2pix#16]
Is the exact same image augmentation on the A and B datasets？

**Comment by zcemycl** [comment]
@momo-love Yes. This algorithm is to map A data to B data, each real image in dataset A has a colormap correspondence in dataset B.

**Comment by justinpinkney** [comment]
@zcemycl Thanks for responding but I've edited your comment a little. Please let's keep the tone friendly. 

@momo-love As suggested if you'd like to know more the original paper is a great starting point: https://phillipi.github.io/pix2pix/
