### ISSUE TITLE
Add random rotation to data augmentation

### ISSUE THREAD

**Issue by corona-discharge** [matlab-deep-learning/pix2pix#17]
I noticed the code applied random cropping and horizontal flipping to data augmentation. How can I modify the code to add random rotation to augment images?

**Comment by justinpinkney** [comment]
Yes it should be as straightforward as adding to this line: https://github.com/matlab-deep-learning/pix2pix/blob/dec1f666edf0858acee990701ea601376f756435/code/%2Bp2p/train.m#L42-L43

Simply pass any extra parameters which the [ImageDataAugmenter](https://www.mathworks.com/help/deeplearning/ref/imagedataaugmenter.html) can take. So in your case I'd suggest adding `RandRotation` and a pair of values

**Comment by corona-discharge** [comment]
Thanks！The code worked successfully.
