### ISSUE TITLE
pix2pix Matlab with .mat files

### ISSUE THREAD

**Issue by abaydou1** [matlab-deep-learning/pix2pix#3]
Hey,

Thanks for posting the code.

I am trying it now with inputs and outputs as .mat file and the code is crashing.
I tried many troubleshooting strategies but none are working.

Do you have an idea how to adjust the code for .mat files ?

Thanks

**Comment by abaydou1** [comment]
I ended up by using a matRead file and it worked. I will close this issue

**Comment by justinpinkney** [comment]
Out of interest what did you have in the .mat files? The raw image arrays or filenames or something else?

**Comment by abaydou1** [comment]
Hey Justin,

Thanks for your reply. In the .mat files I had 144*144*1 grey value single
images. As I said earlier, I used the same strategy that was used in the
U-Net segmentation example by inserting the matread file into the Fcn at
the image datastore.

I am trying to clarify further your code, and I had the following comments:

1- By only asking to set ARange, and BRange, you are assuming that the
lower range of images is always 0. Since this is the case, why did you
choose to use tanh in making a fake image in line 117, why not use sigmoid ?

2 - The normalization steps used in PairedImageDatastore are not
straightforward (Lines 128 - 131). These operations might alter the values
in case images are already normalized. I ended up by making aOut = aIn, and
bOut = bIn. Also in my experience, I had to manually adjusted the sizes in
this function (lines 34:37).

3 - I am puzzled about the line 129 for labels in train function. It seems
to me that you add a series of ones to be used as labels in the dLoss. What
is the idea of using labels here ?

4 - If theoretically this pix2pix is a variant of Conditional GAN, we
should be looking at inserting labels or classes for each image.Do the
labels mentioned in question 2 correspond to the conditional GAN labels and
you have assumed it is always 1 ? If yes, why ? Up to my knowledge, other
coding repositories have enabled the generator with 2 outputs. One output
with sigmoid as you did, and another output with softmax to predict class
labels when not fed into the network.

*I will be grateful if you can clarify the points 3 and 4 further.*

Thanks,
Atallah

**Comment by justinpinkney** [comment]
For others wanting to do a similar thing in future, then I think this is the example being referred to: https://uk.mathworks.com/help/vision/examples/multispectral-semantic-segmentation-using-deep-learning.html

**Comment by abaydou1** [comment]
Actually, the U-net example being referred to is the 3D unet example on this link below: 

https://www.mathworks.com/help/images/segment-3d-brain-tumor-using-deep-learning.html

The strategy for including .mat images is the one copied below:

volReader = @(x) matRead(x);
volLoc = fullfile(preprocessDataLoc,'imagesTr');
volds = imageDatastore(volLoc, ...
    'FileExtensions','.mat','ReadFcn',volReader);

**Comment by justinpinkney** [comment]
Thanks for the clarification Atallah!

**Comment by CHAHI24680** [comment]
Dear Pr. Justin Pinkney
Thank you for posting the code. Is there a way to retrain the model from the latest version of network checkpoints?
