### ISSUE TITLE
Plot utility does not work in number of input Channels is different than 1 or 3

### ISSUE THREAD

**Issue by abaydou1** [matlab-deep-learning/pix2pix#5]
Hey Justin,

It seems that the plot utility during training does not work when the Input channels is different than 1 or 3. I tried with inputs having 2 channels and it did not.

Do you have a quick fix for that ? 

Thanks,
Atallah

**Comment by justinpinkney** [comment]
That's right, the plot expects images to have 1 or 3 channels. What would you expect for a 2 channel image? To display in the R and G channels of an RGB image perhaps, or to show the two channels separately side by side?

**Comment by abaydou1** [comment]
So my channels number depends on the Data I am feeding to the network, and as you probably have inferred, they are not RGB images. I think if the plot can display the First channel of the input regardless of the number of channels, it will be good.

**Comment by abaydou1** [comment]
By the way, do you think that this code might have any pitfall that makes it non suitable for 2 channels input ?

**Comment by justinpinkney** [comment]
This has been added with the behaviour you described above in the recent update.

There shouldn't be anything in particular that would not be suitable for 2 channel input.

**Comment by abaydou1** [comment]
Thanks Justin!!
